[build]
plan = [
  { source = "./backend", name = "backend" },
  { source = "./frontend", name = "frontend" }
]

[run]
processes = [
  { name = "backend", command = "cd backend && npm start", port = 5000 },
  { name = "frontend", command = "cd frontend && npm start", port = 3000 }
]
